name: Docs CI

### Run on *EVERY* commit. The documentation *SHOULD* stay valid, and
### the developers should receive early warning if they break it.
on: [push, pull_request]

jobs:
  check-markdown:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      VFLAGS: -cc tcc
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v

    - name: Build local v
      run: make -j4 && sudo ./v symlink

    - name: Check markdown line length & code examples
      run: ./v check-md -hide-warnings .
      ## NB: -hide-warnings is used here, so that the output is less noisy,
      ## thus real errors are easier to spot.

  report-missing-fn-doc:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      MOPTIONS: --relative-paths --exclude /tests/
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build local v
        run: make -j4 && sudo ./v symlink

      - name: Checkout vab
        uses: actions/checkout@v2
        with:
          path: vab

      - name: Checkout previous vab
        uses: actions/checkout@v2
        with:
          repository: vlang/vab
          ref: master
          path: pvab

      - name: Check against parent commit
        run: |
          ./v missdoc --diff $MOPTIONS pvab vab
